version: 2

sources:
  - name: jaffle_shop                             # alias for the source (used in source() references)
    database: dbt-tutorial                        # e.g Google BigQuery project ID where the source data resides
    schema: jaffle_shop                           # e.g Google dataset ID
    description: Data loaded into our datawarehouse from source systems 
    tables:
      - name: customers
        description: Table comtaining individual customer records
      - name: orders
        description: Table containing individual customer orders
  
  - name: stripe                                  # alias for the source (used in source() references)
    database: dbt-tutorial                        # e.g Google BigQuery project ID where the source data resides
    schema: stripe                                # e.g Google dataset ID
    description: Data loaded into our datawarehouse from source systems 
    tables:
      - name: payment
        description: Table containing individual customer's payment information
      